"""
SIH26124: Simulated GPS Geo-Tagger Module
Provides deterministic GPS route interpolation along simulated transit corridors.

IMPORTANT DISCLOSURE:
Coordinates generated by this module are SIMULATED for MVP demonstration.
All outputs are explicitly flagged with gps_mode="SIMULATED".
"""
import json
from pathlib import Path
from typing import Dict, Any, List, Tuple, Optional
from config import settings

class GeoTagger:
    """
    Simulates bus route GPS trajectory by interpolating coordinates across video frames.
    """
    DEFAULT_WAYPOINTS = [
        {"index": 0, "segment_name": "Sector 4 Junction", "latitude": 28.613900, "longitude": 77.209000},
        {"index": 1, "segment_name": "Outer Ring Road North", "latitude": 28.615500, "longitude": 77.211500},
        {"index": 2, "segment_name": "Outer Ring Road Mid-1", "latitude": 28.617800, "longitude": 77.214000},
        {"index": 3, "segment_name": "Metro Flyover Approach", "latitude": 28.620200, "longitude": 77.217200},
        {"index": 4, "segment_name": "Transit Station Gate 2", "latitude": 28.623000, "longitude": 77.220500},
        {"index": 5, "segment_name": "Commercial District Ave", "latitude": 28.625800, "longitude": 77.224100},
        {"index": 6, "segment_name": "Underpass North Exit", "latitude": 28.628500, "longitude": 77.227800},
        {"index": 7, "segment_name": "Hospital Crossing Link", "latitude": 28.631000, "longitude": 77.231200},
        {"index": 8, "segment_name": "University South Gate", "latitude": 28.634200, "longitude": 77.235000},
        {"index": 9, "segment_name": "Sector 12 Terminal", "latitude": 28.637500, "longitude": 77.239200}
    ]

    def __init__(self, route_file_path: Optional[str] = None):
        self.route_file = Path(route_file_path) if route_file_path else settings.SAMPLE_GPS_ROUTE_PATH
        self.route_id = "ROUTE-7B-SIMULATED"
        self.route_name = "Simulated Ring Road Transit Corridor"
        self.waypoints: List[Dict[str, Any]] = self.DEFAULT_WAYPOINTS
        self.is_simulated: bool = True
        self.load_route()

    def load_route(self) -> None:
        """Load simulated GPS waypoints from JSON file if available."""
        if self.route_file.exists():
            try:
                with open(self.route_file, "r", encoding="utf-8") as f:
                    data = json.load(f)
                    self.route_id = data.get("route_id", self.route_id)
                    self.route_name = data.get("route_name", self.route_name)
                    self.is_simulated = data.get("is_simulated", True)
                    pts = data.get("waypoints", [])
                    if len(pts) >= 2:
                        self.waypoints = pts
            except Exception:
                self.waypoints = self.DEFAULT_WAYPOINTS

    def get_coordinate_for_frame(self, frame_index: int, total_frames: int) -> Dict[str, Any]:
        """
        Interpolate simulated GPS latitude and longitude based on frame index and total frames.

        Returns:
            Dict with latitude, longitude, segment_name, and gps_mode="SIMULATED".
        """
        if total_frames <= 1:
            wp = self.waypoints[0]
            return {
                "latitude": round(wp["latitude"], 6),
                "longitude": round(wp["longitude"], 6),
                "segment_name": wp.get("segment_name", "Segment 0"),
                "gps_mode": "SIMULATED",
                "route_id": self.route_id
            }

        progress = max(0.0, min(1.0, float(frame_index) / float(total_frames - 1)))
        
        num_segments = len(self.waypoints) - 1
        segment_float = progress * num_segments
        segment_idx = int(segment_float)
        
        if segment_idx >= num_segments:
            wp = self.waypoints[-1]
            return {
                "latitude": round(wp["latitude"], 6),
                "longitude": round(wp["longitude"], 6),
                "segment_name": wp.get("segment_name", f"Segment {num_segments}"),
                "gps_mode": "SIMULATED",
                "route_id": self.route_id
            }

        t = segment_float - segment_idx
        wp_start = self.waypoints[segment_idx]
        wp_end = self.waypoints[segment_idx + 1]

        lat = wp_start["latitude"] + t * (wp_end["latitude"] - wp_start["latitude"])
        lon = wp_start["longitude"] + t * (wp_end["longitude"] - wp_start["longitude"])
        seg_name = wp_start.get("segment_name", f"Segment {segment_idx}")

        return {
            "latitude": round(lat, 6),
            "longitude": round(lon, 6),
            "segment_name": seg_name,
            "gps_mode": "SIMULATED",
            "route_id": self.route_id
        }
