"""
SIH26124: Road Damage Detector Module
Detects road surface damage / potholes using pretrained YOLOv8 with explicit mode tracking:
- REAL_AI: Active model weights loaded, inferences generated strictly by the model.
- DEMO_SIMULATION: Fallback mode used only when model weights are unavailable.
"""
import time
from pathlib import Path
from typing import List, Dict, Any, Optional
import numpy as np
import cv2
from ultralytics import YOLO
from config import settings

class RoadDamageDetector:
    """
    Road Damage / Pothole Detector.
    Supports REAL_AI and DEMO_SIMULATION modes with transparent disclosure.
    """
    # Color palette based on prototype severity heuristic (BGR format)
    SEVERITY_COLORS = {
        "high": (0, 0, 230),     # Red
        "medium": (0, 140, 255),  # Orange
        "low": (0, 215, 255)     # Yellow
    }

    def __init__(
        self,
        model_path: Optional[str] = None,
        conf_threshold: float = 0.30,
        force_demo_mode: bool = False
    ):
        """
        Initialize the Road Damage Detector.
        """
        self.conf_threshold = conf_threshold
        self.force_demo_mode = force_demo_mode
        self.model = None
        self.load_time_sec = 0.0
        self.detection_mode = "DEMO_SIMULATION"
        self.model_name = "None (Simulation Mode)"

        if not force_demo_mode:
            # Determine target weights path
            if model_path is not None:
                target_weights = Path(model_path)
            else:
                target_weights = settings.MODELS_DIR / "road_damage_yolov8.pt"
                if not target_weights.exists():
                    target_weights = settings.MODELS_DIR / "pothole_samdutse.pt"

            if target_weights.exists():
                try:
                    start_load = time.perf_counter()
                    self.model = YOLO(str(target_weights))
                    self.load_time_sec = time.perf_counter() - start_load
                    self.detection_mode = "REAL_AI"
                    self.model_name = target_weights.name
                except Exception as e:
                    self.detection_mode = "DEMO_SIMULATION"
                    self.model = None
            else:
                self.detection_mode = "DEMO_SIMULATION"
        else:
            self.detection_mode = "DEMO_SIMULATION"

    @property
    def mode_disclosure_text(self) -> str:
        """User-facing disclosure text regarding the active detection mode."""
        if self.detection_mode == "REAL_AI":
            return f"REAL AI MODE — Inferences generated by {self.model_name}"
        return "DEMO/SIMULATION MODE — Events are simulated and are NOT AI detections."

    def calculate_severity(self, bbox: List[float], frame_width: int, frame_height: int) -> str:
        """
        Prototype severity heuristic based on relative bounding box area.
        NOTE: This is a hackathon prototype heuristic, not an official municipal standard.
        - Area >= 4.0% of frame -> high
        - Area between 1.5% and 4.0% -> medium
        - Area < 1.5% -> low
        """
        if frame_width <= 0 or frame_height <= 0:
            return "low"

        x1, y1, x2, y2 = bbox
        box_area = max(0.0, (x2 - x1)) * max(0.0, (y2 - y1))
        frame_area = float(frame_width * frame_height)
        area_pct = (box_area / frame_area) * 100.0

        if area_pct >= 4.0:
            return "high"
        elif area_pct >= 1.5:
            return "medium"
        return "low"

    def detect(self, frame: np.ndarray) -> Dict[str, Any]:
        """
        Run road damage inference on a single frame.
        """
        if frame is None or frame.size == 0:
            return {"detections": [], "inference_time_ms": 0.0, "detection_mode": self.detection_mode}

        h, w = frame.shape[:2]

        if self.detection_mode == "REAL_AI" and self.model is not None:
            start_inf = time.perf_counter()
            results = self.model.predict(
                source=frame,
                conf=self.conf_threshold,
                device="cpu",
                verbose=False
            )
            inf_time_ms = (time.perf_counter() - start_inf) * 1000.0

            detections: List[Dict[str, Any]] = []
            if results and len(results) > 0:
                boxes = results[0].boxes
                if boxes is not None:
                    for box in boxes:
                        cls_id = int(box.cls[0].item())
                        conf = float(box.conf[0].item())
                        xyxy = [round(float(v), 2) for v in box.xyxy[0].tolist()]
                        
                        raw_name = self.model.names.get(cls_id, "pothole")
                        class_name = "pothole" if str(raw_name).lower() in ["0", "pothole"] else str(raw_name).lower()
                        severity = self.calculate_severity(xyxy, w, h)

                        detections.append({
                            "class_id": cls_id,
                            "class_name": class_name,
                            "confidence": round(conf, 4),
                            "bbox": xyxy,
                            "severity": severity,
                            "detection_mode": "REAL_AI"
                        })

            return {
                "detections": detections,
                "inference_time_ms": round(inf_time_ms, 2),
                "detection_mode": "REAL_AI"
            }

        else:
            # DEMO / SIMULATION MODE (Used only when model weights are not loaded)
            return {
                "detections": [],
                "inference_time_ms": 0.0,
                "detection_mode": "DEMO_SIMULATION"
            }

    def draw_detections(self, frame: np.ndarray, damage_detections: List[Dict[str, Any]]) -> np.ndarray:
        """
        Draw road damage bounding boxes, severity badges, and mode indicators on the frame.
        """
        annotated = frame.copy()
        for det in damage_detections:
            bbox = det["bbox"]
            x1, y1, x2, y2 = int(bbox[0]), int(bbox[1]), int(bbox[2]), int(bbox[3])
            class_name = det["class_name"]
            conf = det["confidence"]
            severity = det.get("severity", "low").lower()
            color = self.SEVERITY_COLORS.get(severity, (0, 215, 255))

            # Draw prominent damage rectangle with corner markers
            cv2.rectangle(annotated, (x1, y1), (x2, y2), color, 2)

            # Draw severity tag badge
            mode_tag = "" if det.get("detection_mode") == "REAL_AI" else " [SIM]"
            label = f"DAMAGE: {class_name.upper()} {conf*100:.0f}% | {severity.upper()}{mode_tag}"
            (lbl_w, lbl_h), _ = cv2.getTextSize(label, cv2.FONT_HERSHEY_SIMPLEX, 0.45, 1)

            top_y = max(y1 - lbl_h - 6, 0)
            cv2.rectangle(annotated, (x1, top_y), (x1 + lbl_w + 6, top_y + lbl_h + 6), color, -1)
            cv2.putText(
                annotated,
                label,
                (x1 + 3, top_y + lbl_h + 2),
                cv2.FONT_HERSHEY_SIMPLEX,
                0.45,
                (0, 0, 0),
                1,
                cv2.LINE_AA
            )

        return annotated
